[tool.poetry]
name = "smart-tg-bot"
version = "0.1.0"
description = ""
authors = ["Fiodar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
